table dfiq_manager_summary
	lineageTag: 86529cbd-65a2-4234-b824-929f14e76548

	measure 'M.Top10PctAvgPayoutPrevQ' =
			
			VAR prevIdx = [M.Selected Quarter Index] - 1
			VAR RepsPrevQ =
			    CALCULATETABLE (
			        VALUES ( dfiq_manager_summary[emp_id] ),
			        REMOVEFILTERS ( DimQuarter ),
			        KEEPFILTERS ( DimQuarter[QuarterIndex] = prevIdx )
			    )
			VAR RepCount = COUNTROWS ( RepsPrevQ )
			VAR TopNSize = MAX ( 1, ROUNDUP ( RepCount * 0.10, 0 ) )
			VAR RepsWithEarningsPrevQ =
			    ADDCOLUMNS (
			        RepsPrevQ,
			        "RepEarningsPrevQ",
			            CALCULATE (
			                SUM ( dfiq_manager_summary[emp_total_earnings] ),
			                REMOVEFILTERS ( DimQuarter ),
			                KEEPFILTERS ( DimQuarter[QuarterIndex] = prevIdx )
			            )
			    )
			VAR TopRepsPrevQ =
			    TOPN ( TopNSize, RepsWithEarningsPrevQ, [RepEarningsPrevQ], DESC, dfiq_manager_summary[emp_id], ASC )
			VAR AvgTop10 = AVERAGEX ( TopRepsPrevQ, [RepEarningsPrevQ] )
			RETURN IF ( RepCount = 0, BLANK (), AvgTop10 )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 5032fa73-0a18-4f0b-9927-41cd3412d502

	measure 'M.Icon_TotalComp' =
			
			var positive=UNICHAR(8593)
			var Negative=UNICHAR(8595)
			var Result=If ([M3.ChangeFromPreviousEarnings]>0,positive,Negative)
			RETURN
			Result
		lineageTag: b94d3b70-918a-4182-9b18-1a2b053163aa

	measure 'M.IconColourEarning' = If([M3.ChangeFromPreviousEarnings]>0,"Green","Red")
		lineageTag: f04849e0-c7a7-4882-a12f-cbe043f850e4

	measure 'M1.TotalEarnings' =
			
			SUM(dfiq_manager_summary[post_eligibility_earnings])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 7b85dd15-4d7a-4eaa-ba40-09e8108c9ef2

	measure 'M1.TotalPayout' =
			
			SUM(dfiq_manager_summary[earning_percent])
		lineageTag: 51fe664c-ccb6-4154-82c1-2f5c7704c7ab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'M2.PreviousQuarterEarnings' =
			
			VAR selIdx  = [M.Selected Quarter Index]
			VAR prevIdx = selIdx - 1
			VAR prevVal =
			    CALCULATE(
			        SUM ( dfiq_manager_summary[post_eligibility_earnings] ),
			        REMOVEFILTERS ( DimQuarter ),             -- ignore current quarter selection
			        DimQuarter[QuarterIndex] = prevIdx        -- apply previous quarter only
			    )
			RETURN COALESCE ( prevVal, 0 )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 11e23a1c-20d4-49d2-b9e8-e1fd324fc9c7

	measure 'M2.PreviousQuarterPayout' = ```
			
			VAR CurrentQuarter = SELECTEDVALUE(dfiq_manager_summary[quarter])
			VAR CurrentYear = RIGHT(CurrentQuarter, 4)
			VAR CurrentQ = LEFT(CurrentQuarter, 2)
			
			VAR PrevQ = 
			    SWITCH(CurrentQ,
			        "Q1", "Q4",
			        "Q2", "Q1",
			        "Q3", "Q2",
			        "Q4", "Q3"
			    )
			
			VAR PrevYear = 
			    IF(CurrentQ = "Q1", VALUE(CurrentYear) - 1, VALUE(CurrentYear))
			
			VAR PrevQuarterLabel = PrevQ & " " & FORMAT(PrevYear, "0000")
			
			RETURN
			CALCULATE(
			    SUM(dfiq_manager_summary[earning_percent]),
			    dfiq_manager_summary[quarter] = PrevQuarterLabel
			)
			```
		lineageTag: 61b2e648-842a-4f07-84f9-40a0e1acc4d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'M3.ChangeFromPreviousEarnings' =
			
			DIVIDE([M1.TotalEarnings] - [M2.PreviousQuarterEarnings], [M2.PreviousQuarterEarnings], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2e8c44ea-e35a-4ca3-8ee7-9de4334b5ea2

	measure ChangeFromPreviousTop10Payout =
			
			DIVIDE([Top10AvgPayout_CurrentQ] - [Top10AvgPayout_PrevQ], [Top10AvgPayout_PrevQ], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 54a9f134-dee8-4f25-aa99-cb7d7389dacc

	measure AvgAtt% = AVERAGE(dfiq_manager_summary[attainment])/COUNT(dfiq_manager_summary[emp_id])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c7bd0eb0-5f84-4e4e-9149-4fafbf0b3e8e

	measure 'M.Icon.Payout' = ```
			
			VAR s = [M.Earnings_ChangeSign]
			RETURN
			SWITCH (
			    TRUE(),
			    ISBLANK(s), UNICHAR(8212),    
			    s = -1,    UNICHAR(8595),      
			               UNICHAR(8593)       
			)
			```
		lineageTag: f35e10f5-a542-4663-882b-b5e07fb66b15

	measure 'M.IconColour.Top10%' = If([ChangeFromPreviousTop10Payout]>0,"Green","Red")
		lineageTag: 7b99e94b-11b5-452f-9d0c-e950de687f3b

	measure 'M2.PreviousQuarterAttainment %' =
			
			VAR prevIdx = [M.Selected Quarter Index] - 1
			RETURN
			COALESCE (
			    CALCULATE (
			        [M1.PresentQuarterAttainment],        -- use your working current-attainment measure
			        REMOVEFILTERS ( DimQuarter ),         -- ignore current quarter only
			        KEEPFILTERS ( DimQuarter[QuarterIndex] = prevIdx )   -- apply previous quarter
			    ),
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9848205f-6982-420f-82ad-dba7e93a9046

	measure ChangeFromPreviousAttainment =
			
			VAR Cur  = [M1.PresentQuarterAttainment]
			VAR Prev = [M2.PreviousQuarterAttainment %]
			RETURN
			IF ( ISBLANK ( Prev ), BLANK(), DIVIDE ( Cur - Prev, Prev ) )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 08f4da61-4393-4d7d-a535-6fbd498eb1de

	measure 'M1.TotalAttainment' =
			
			AVERAGE(dfiq_manager_summary[attainment])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: af5e274c-158b-482c-a05c-c6be3a0f9542

	measure 'M.Icon.Attainment' =
			var positive=UNICHAR(8593)
			var Negative=UNICHAR(8595)
			var Result=If ([ChangeFromPreviousAttainment]>0,positive,Negative)
			RETURN
			Result
		lineageTag: 68f99324-43cb-4d6a-94c3-67cc253298dd

	measure 'M.IconTop10%' =
			var positive=UNICHAR(8593)
			var Negative=UNICHAR(8595)
			var Result=If ([ChangeFromPreviousTop10Payout]>0,positive,Negative)
			RETURN
			Result
		lineageTag: a437782f-e46d-4340-ad24-7c5d55d269f9

	measure 'M3.ChangeFromPreviousPayout' =
			
			DIVIDE([M.Totalemp_count]-[M3.changefrom prev_emp count],[M3.changefrom prev_emp count],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4c2a85c8-5b72-48bd-9ea7-4fcdb2d3857b

	measure 'M.IconColour.Payout' = If([M3.ChangeFromPreviousPayout]>0,"Green","Red")
		lineageTag: c9661b27-9c76-441e-bf46-108d49613deb

	measure 'M.IconColour.Attainment' = If([ChangeFromPreviousAttainment]>0,"Green","Red")
		lineageTag: aa00bf4f-8207-43e0-ac72-0d8487b599c7

	measure 'M.IconColour.Top10%Payout' = If([ChangeFromPreviousTop10Payout]>0,"Green","Red")
		lineageTag: 803a7285-d59c-4f00-bffd-ab6cbe358d3b

	measure 'IconColour.Bottom10%' = If([ChangeFromPreviousBottom10Payout]>0,"Green","Red")
		lineageTag: b5c84887-fdce-44af-813d-48c4b5a54fb8

	measure ChangeFromPreviousBottom10Payout =
			
			DIVIDE([Bottom10AvgPayout_CurrentQ] - [Bottom10AvgPayoutPrevQ], [Bottom10AvgPayoutPrevQ], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0ef4d6ed-d1a6-4368-a739-5cbc270edd76

	measure IconBottom10% =
			var positive=UNICHAR(8593)
			var Negative=UNICHAR(8595)
			var Result=If ([ChangeFromPreviousBottom10Payout]>0,positive,Negative)
			RETURN
			Result
		lineageTag: 43536bdd-4047-4bd2-b42d-3372393156d5

	measure AvgPayout = ```
			sum(dfiq_manager_summary[post_eligibility_earnings]) / DISTINCTCOUNT(dfiq_manager_summary[manager_name])
			
			```
		formatString: 0%;-0%;0%
		lineageTag: 5f5a29df-07c1-4e00-ae15-5c717677624b

	measure 'M.Totalemp_count' = DISTINCTCOUNT(dfiq_manager_summary[emp_id])
		formatString: 0
		lineageTag: e8ccc1cc-caf4-499a-b4b9-08f1adb42117

	measure 'M3.changefrom prev_emp count' =
			
			DIVIDE((IF([AvgPayout]>1,[M.Totalemp_count])) - (IF([AvgPayout]>1,[M2.PreviousQuarterEmpid_payout])), (IF([AvgPayout]>1,[M2.PreviousQuarterEmpid_payout])), 0)
		lineageTag: 9857b10b-6cdd-4166-bff5-2bfa880e2c2e

	measure 'M2.PreviousQuarterEmpid_payout' = ```
			
			VAR CurrentQuarter = SELECTEDVALUE(dfiq_manager_summary[quarter])
			VAR CurrentYear = RIGHT(CurrentQuarter, 4)
			VAR CurrentQ = LEFT(CurrentQuarter, 2)
			
			VAR PrevQ = 
			    SWITCH(CurrentQ,
			        "Q1", "Q4",
			        "Q2", "Q1",
			        "Q3", "Q2",
			        "Q4", "Q3"
			    )
			
			VAR PrevYear = 
			    IF(CurrentQ = "Q1", VALUE(CurrentYear) - 1, VALUE(CurrentYear))
			
			VAR PrevQuarterLabel = PrevQ & " " & FORMAT(PrevYear, "0000")
			
			VAR _val =
			    CALCULATE(
			        DISTINCTCOUNT(dfiq_manager_summary[emp_id]),
			        KEEPFILTERS(dfiq_manager_summary[quarter] = PrevQuarterLabel),
			        -- remove the next line if you want ALL reps, keep it if you want ≥200% only
			        dfiq_manager_summary[earning_percent] >= 200
			    )
			RETURN
			    COALESCE(_val, 0)
			```
		formatString: 0
		lineageTag: 1d609a91-6607-4687-a7b4-fd63d564b7f2

	measure 'Actual (TRx)' =
			
			SUM( dfiq_manager_summary[baseline_sales] )
		formatString: #,0
		lineageTag: 6efd1ada-de49-4ce0-be86-5a2027f01c85

	measure 'Payout $' =
			
			SUM( dfiq_manager_summary[post_eligibility_earnings] )
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7b01aee0-8e9b-4dc5-96d2-8315d2d2665c

	measure 'Payout %' = AVERAGE( dfiq_manager_summary[earning_percent] )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 90c9ef17-a309-47cb-9eb1-61340d93bb1a

	measure 'IC Eligibility %' =
			
			VAR v = AVERAGE( dfiq_manager_summary[eligibility] )
			RETURN IF( v > 1, v / 100.0, v )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 86904363-bf48-4859-9377-20392ef46e0e

	measure 'Earning %' =
			
			AVERAGE ( dfiq_manager_summary[earning_percent] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 00b28ff0-c96c-4043-b01a-d3b751d37b3e

	measure 'QTD Sales' =
			
			SUM ( 'dfiq_manager_summary'[baseline_sales] )
		lineageTag: 7d4d2371-eb50-4469-bd39-12e6f2cc6754

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Goals' =
			
			SUM ( 'dfiq_manager_summary'[simulated_goals] )
		lineageTag: 37adbfe8-30dd-4842-9d89-c2ae8a7249b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'M.Correlation r (Sales vs Goals)' =
			
			VAR Points =
			    FILTER(
			        ADDCOLUMNS(
			            VALUES ( dfiq_manager_summary[emp_id] ),   -- use rep_id/territory if that's your dot
			            "x", [M.Sales (QTD)],
			            "y", [M.Goals (QTD)]
			        ),
			        NOT ISBLANK ( [x] ) && NOT ISBLANK ( [y] )
			    )
			VAR n       = COUNTROWS ( Points )
			VAR sum_x   = SUMX ( Points, [x] )
			VAR sum_y   = SUMX ( Points, [y] )
			VAR sum_xy  = SUMX ( Points, [x] * [y] )
			VAR sum_x2  = SUMX ( Points, [x] * [x] )
			VAR sum_y2  = SUMX ( Points, [y] * [y] )
			VAR num     = n * sum_xy - sum_x * sum_y
			VAR den     = SQRT ( n * sum_x2 - sum_x * sum_x ) * SQRT ( n * sum_y2 - sum_y * sum_y )
			RETURN
			    IF ( n < 2 || den = 0, BLANK (), DIVIDE ( num, den ) )
		lineageTag: 84d19380-2941-4955-8d3a-6bf43a9cd045

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'M.Correlation Label' =
			
			VAR r = [M.Correlation r (Sales vs Goals)]
			RETURN IF(
			    ISBLANK(r),
			    "Goal Attainment Correlation : N/A",
			    "Goal Attainment Correlation : " & FORMAT(r, "0.00%")
			)
		lineageTag: 8bea94a6-888f-4025-9ef7-e56c3ca58459

	measure 'QTD Sales (TRx)' = DIVIDE( [QTD Sales], 1000 )
		formatString: 0
		lineageTag: 7ec60dbd-0f2f-45e3-9084-2c160e481521

	measure 'QTD Goals (TRx)' = DIVIDE( [QTD Goals], 1000 )
		formatString: 0
		lineageTag: 7e35df39-7dd6-4e26-b03d-e36f939514f1

	measure 'Total Reps' = DISTINCTCOUNT(dfiq_manager_summary[emp_id])
		formatString: 0
		lineageTag: e8a82906-5aac-45d2-acd9-d1b606697646

	measure 'Team Name (Proper)' =
			
			VAR _team = SELECTEDVALUE(dfiq_manager_summary[team_name])
			RETURN
			IF(
			    NOT(ISBLANK(_team)),
			    UPPER(LEFT(_team, 1)) & LOWER(MID(_team, 2, LEN(_team))),
			    BLANK()
			)
		lineageTag: 77093906-ac07-4939-9219-1c12e0d82bdc

	measure 'Attainment %' =
			
			DIVIDE( [Actual (TRx)], [Goals (TRx)] )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 83fa5f08-1827-4a7d-80cd-110958da388d

	measure 'Goals (TRx)' =
			
			SUM( dfiq_manager_summary[simulated_goals] )
		formatString: #,0
		lineageTag: e49566df-a897-4adf-87e7-4d6999b14871

	measure 'Payout Band' =
			
			SWITCH( TRUE(),
			    [Payout %] >= 1, "Up",
			    [Payout %] >= 0.9, "Flat",
			    "Down"
			)
		lineageTag: bfa46619-b6db-4757-b407-55257a3a2851

	measure 'Selected View' =
			
			SELECTEDVALUE ( 'Perf View'[View], "Top" )
		lineageTag: bc8ce08b-a97b-4474-8290-960129c447f8

	measure 'Reps (Distinct)' = DISTINCTCOUNT ( dfiq_manager_summary[emp_name] )
		formatString: 0
		lineageTag: 3ee710ac-3cc2-491b-b858-475d70535c5d

	measure 'Avg Payout' =
			
			DIVIDE (
			    SUM ( dfiq_manager_summary[post_eligibility_earnings] ),
			    [Reps (Distinct)]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 722695df-eac0-47ef-a83f-5d2e079e9cc6

	measure 'Bottom Value' =
			
			VAR BottomRank =
			    MAX ( 'dfiq_manager_summary'[emp_rank_bottom10] )   -- 1 = worst, 10 = 10th worst
			RETURN
			IF (
			    NOT ISBLANK ( BottomRank )
			        && BottomRank <= 5,
			    [Earning %]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9a7df212-a151-4c61-a920-168627a3a15a

	measure 'Selected Metric %' = ```
			
			VAR _metric = SELECTEDVALUE('Metric Toggle'[Metric], "Payout")
			VAR _payout = CALCULATE(AVERAGE(dfiq_manager_summary[earning_percent]))
			VAR _att = CALCULATE(AVERAGE(dfiq_manager_summary[attainment])) 
			RETURN
			    SWITCH(
			        _metric,
			        "Payout", _payout,
			        "Attainment", _att,
			        _payout
			    )
			```
		lineageTag: 910752bb-71b0-45c8-a472-11e7e9b69387

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reps in Bucket' =
			
			VAR _min = MIN(Buckets[MinInc])
			VAR _max = MAX(Buckets[MaxExc])
			VAR _repTable =
			    ADDCOLUMNS(
			        VALUES(dfiq_manager_summary[emp_id]),
			        "val", CALCULATE([Selected Metric %])
			    )
			VAR _count =
			    COUNTROWS(
			        FILTER(_repTable, [val] >= _min && [val] < _max)
			    )
			RETURN
			    IF(ISBLANK(_count), 0, _count)
		formatString: 0
		lineageTag: bd8ba36f-f308-40e0-aa6d-4c2a635cfb14

	measure 'Axis Subtitle' =
			
			VAR _metric = SELECTEDVALUE('Metric Toggle'[Metric], "Payout")
			RETURN
			    SWITCH(
			        _metric,
			        "Payout", "Payout % Buckets",
			        "Attainment", "Attainment % Buckets",
			        "Distribution"
			    )
		lineageTag: dbc8d3e1-a81d-453b-960b-20a873108df4

	measure 'Avg Payout(PC)' =
			
			DIVIDE(
			    SUM(dfiq_manager_summary[post_eligibility_earnings]),
			    DISTINCTCOUNT(dfiq_manager_summary[emp_id])
			)
		lineageTag: b147a336-9513-4707-a79c-6b593172fb3f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Payout %(PC)' =
			
			AVERAGEX (
			    VALUES ( dfiq_manager_summary[emp_id] ),
			    DIVIDE (
			        CALCULATE ( SUM ( dfiq_manager_summary[post_eligibility_earnings] ) ),
			        CALCULATE ( SUM ( dfiq_manager_summary[target] ) )
			    )
			)
		formatString: 0%;-0%;0%
		lineageTag: e9a8b4fa-f974-4398-bd54-cbbd4f6c8a93

	measure 'Show Top' =
			
			IF ( [Selected View] = "Top", 1, 0 )
		formatString: 0
		lineageTag: 010fc1ec-67b0-4914-a5bc-e5fd64040e36

	measure 'Show Bottom' =
			
			IF ( [Selected View] = "Bottom", 1, 0 )
		formatString: 0
		lineageTag: ccf153c5-ff71-456e-83ff-59fe1a49fa6d

	measure 'M1.PresentQuarterAttainment' =
			
			AVERAGE ( dfiq_manager_summary[attainment] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f9feac1f-21d7-4479-a171-9e8a4bcd4499

	measure 'M3.ChangeFromPreviousPayout_Sign' =
			
			VAR d = [M3.ChangeFromPreviousPayout]           -- your % change measure
			VAR tol = 0.000001                              -- treat |d| < 0.0001% as zero
			RETURN
			IF ( ISBLANK(d), BLANK(),
			     IF ( d >  tol,  1,
			     IF ( d < -tol, -1, 0 ) ) )
		formatString: 0
		lineageTag: 5138f33d-747a-42c8-b893-ae84371cff13

	measure 'M.Icon.Payout Color' =
			
			VAR s = [M3.ChangeFromPreviousPayout_Sign]
			RETURN
			SWITCH ( TRUE(),
			    ISBLANK(s), "#9CA3AF",  -- grey for N/A
			    s = -1,    "#DC2626",   -- red  (down)
			    s = 0,     "#2563EB",   -- blue (zero)
			               "#16A34A"    -- green (up)
			)
		lineageTag: 3a386293-a09a-4cd3-aa89-04e93707df6b

	measure 'M.Top10Payout_ChangeSign' = ```
			
			VAR d   = [ChangeFromPreviousTop10Payout]  
			VAR tol = 0.000001                              
			RETURN
			IF ( ISBLANK(d), BLANK(),
			     IF ( d >  tol,  1,
			     IF ( d < -tol, -1, 0 ) ) )
			```
		formatString: 0
		lineageTag: bbff8e51-2876-4e90-a561-1d5644951792

	measure 'M.Icon.Top10Payout' =
			
			VAR s = [M.Top10Payout_ChangeSign]
			RETURN
			SWITCH ( TRUE(),
			    ISBLANK(s), UNICHAR(8212),     -- "—" when no previous
			    s = -1,    UNICHAR(8595),      -- ↓
			               UNICHAR(8593)       -- ↑ for zero or positive
			)
		lineageTag: 17bcc824-a705-4317-b0ba-348e489a359c

	measure 'M.Color.Top10PayoutChange' =
			
			VAR s = [M.Top10Payout_ChangeSign]
			RETURN
			SWITCH ( TRUE(),
			    ISBLANK(s), "#9CA3AF",   -- grey when N/A
			    s = -1,    "#DC2626",    -- red  (down)
			    s = 0,     "#2563EB",    -- blue (zero)
			               "#16A34A"     -- green (up)
			)
		lineageTag: ab8351bf-a9c0-438f-8e05-cc4e95ae5010

	measure 'M.Earnings_ChangeSign' = ```
			
			VAR d   = [M3.ChangeFromPreviousEarnings]  
			VAR tol = 0.000001                         
			RETURN
			IF ( ISBLANK(d), BLANK(),
			     IF ( d >  tol,  1,
			     IF ( d < -tol, -1, 0 ) ) )
			```
		formatString: 0
		lineageTag: fb2f0596-6b43-4e70-96d7-c65845406a78

	measure 'M.Color.Payout' =
			
			SWITCH ( TRUE(),
			    ISBLANK([M.Earnings_ChangeSign]), "#9CA3AF",  -- grey when N/A
			    [M.Earnings_ChangeSign] = -1, "#DC2626",      -- RED for negative
			                           "#16A34A"      -- GREEN for zero or positive
			)
		lineageTag: 384c4cf8-b57e-4c6e-9720-1a7b7e4bc03b

	measure 'M.Sign.Payout' =
			
			VAR d   = [M3.ChangeFromPreviousPayout]   // your change% measure
			VAR tol = 0.000001                        // ~0.0001% tolerance
			RETURN IF ( ISBLANK(d), BLANK(),
			           IF ( d >  tol,  1,
			           IF ( d < -tol, -1, 0 ) ) )
		formatString: 0
		lineageTag: 81ed08ec-b192-4879-b095-229cc1ee280f

	measure 'M.Icon.Payout2' = ```
			
			VAR s = [M.Sign.Payout]
			RETURN
			SWITCH ( TRUE(),
			    ISBLANK(s), UNICHAR(8212),    // —
			    s = -1,    UNICHAR(8595),     // ↓
			               UNICHAR(8593) )  
			```
		lineageTag: 4d775523-b498-4530-a5ae-c90d2efb87a5

	measure 'M.Color.Payout2' = ```
			
			SWITCH ( TRUE(),
			    ISBLANK([M.Sign.Payout]), "#9CA3AF",  // grey N/A
			    [M.Sign.Payout] = -1, "#DC2626",      // red
			                         "#16A34A" )  
			```
		lineageTag: 6541bcc0-1d6d-4f9e-a9f8-99c53bab42b4

	measure 'Title Quarter Text' =
			
			VAR _q =
			    COALESCE(
			        SELECTEDVALUE('DimQuarter'[quarter]),
			        SELECTEDVALUE(dfiq_manager_summary[quarter])
			    )
			RETURN
			IF(NOT ISBLANK(_q), _q, "All Quarters")
		lineageTag: 431512c3-5e7d-41f1-bf3c-134d762e5a3e

	measure 'Title.ManagerSummary' =
			
			[Title Quarter Text] & " Manager Summary"
		lineageTag: 8a05594a-e5e4-4339-9896-98c0497eba6d

	measure 'M.Reps' = DISTINCTCOUNT ( dfiq_manager_summary[emp_id] )
		formatString: 0
		lineageTag: 938f9c73-43a5-4359-bf89-19ccf881c645

	measure 'M.Avg Payout %' =
			
			DIVIDE ( SUM ( dfiq_manager_summary[earning_percent] ), [M.Reps] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e02d1633-3423-4601-bd8d-17d310064fed

	measure 'M.Avg Payout (₹/rep)' =
			
			DIVIDE ( SUM ( dfiq_manager_summary[post_eligibility_earnings] ), [M.Reps] )
		lineageTag: 602c279c-2ff8-4461-a48b-1f72447e6c54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'M.Budget Utilization %' =
			
			DIVIDE (
			    SUM ( dfiq_manager_summary[post_eligibility_earnings] ),
			    SUM ( dfiq_manager_summary[target] )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f7ff8188-e1b6-4bc7-8e26-bde303186f63

	measure 'M.Selected Quarter Index' =
			
			VAR idxWhenSelected =
			    SELECTEDVALUE (
			        'DimQuarter'[QuarterIndex],
			        CALCULATE ( MAX ( 'DimQuarter'[QuarterIndex] ), ALL ( 'DimQuarter' ) )
			    )
			RETURN idxWhenSelected
		lineageTag: 5b603d7a-ec6e-4c91-9ec4-a045aefbb0c1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'M.Include In 6Q Window' =
			
			VAR sel     = [M.Selected Quarter Index]
			VAR minIdx  = CALCULATE ( MIN ( 'DimQuarter'[QuarterIndex] ), ALL ( 'DimQuarter' ) )
			VAR fromIdx = MAX ( sel - 5, minIdx )
			VAR thisIdx = SELECTEDVALUE ( 'DimQuarter'[QuarterIndex] )
			RETURN IF ( NOT ISBLANK ( thisIdx ) && thisIdx >= fromIdx && thisIdx <= sel, 1, 0 )
		formatString: 0
		lineageTag: 3263e84a-4506-40a7-886b-8a525183c399

	measure 'M.Selected Quarter Index (Robust)' =
			
			VAR idxSingle = SELECTEDVALUE('DimQuarter'[QuarterIndex])
			VAR idxMulti  = MAXX(ALLSELECTED('DimQuarter'), 'DimQuarter'[QuarterIndex])
			VAR idxAny    = CALCULATE(MAX('DimQuarter'[QuarterIndex]), ALL('DimQuarter'))
			RETURN COALESCE(idxSingle, idxMulti, idxAny)
		lineageTag: 7e80d1b9-e773-473c-b26b-a61bf441e756

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'M.Include In 6Q Window (Axis)' =
			
			VAR sel     = [M.Selected Quarter Index]
			VAR minIdx  = CALCULATE( MIN(AxisQuarter[QuarterIndex]), ALL(AxisQuarter) )
			VAR fromIdx = MAX(sel - 5, minIdx)
			VAR thisIdx = SELECTEDVALUE(AxisQuarter[QuarterIndex])
			RETURN IF( NOT ISBLANK(thisIdx) && thisIdx >= fromIdx && thisIdx <= sel, 1, 0 )
		formatString: 0
		lineageTag: bb23ce05-933e-417a-adf0-00e638cea83d

	measure 'M.Budget Utilization % (Axis)' =
			
			CALCULATE (
			    [M.Budget Utilization %],
			    REMOVEFILTERS ( DimQuarter ),                              -- ignore slicer’s single quarter
			    TREATAS ( VALUES ( AxisQuarter[quarter] ), dfiq_manager_summary[quarter] )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eea55226-cb37-49eb-bb20-ccc0e681c44c

	measure 'M.Avg Attainment % (Axis)' =
			
			CALCULATE (
			    [M.Avg Attainment %],
			    REMOVEFILTERS ( DimQuarter ),
			    TREATAS ( VALUES ( AxisQuarter[quarter] ), dfiq_manager_summary[quarter] )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 192b8acc-b864-4528-af8f-d687d83a8caa

	measure 'M.Avg Payout % (Axis)' =
			
			CALCULATE (
			    [M.Avg Payout %],
			    REMOVEFILTERS ( DimQuarter ),
			    TREATAS ( VALUES ( AxisQuarter[quarter] ), dfiq_manager_summary[quarter] )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 14b6f795-8e94-48d7-a6ce-dee5309c2075

	measure 'M.Emp Payout (Amount)' = SUM ( dfiq_manager_summary[post_eligibility_earnings] )
		lineageTag: 41f473b0-64a0-41e8-92a8-ff9999714893

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'M.Selected Quarter IndexATT' =
			
			SELECTEDVALUE (
			    DimQuarter[QuarterIndex],
			    CALCULATE ( MAX ( DimQuarter[QuarterIndex] ), ALL ( DimQuarter ) )
			)
		lineageTag: ab533df9-21ef-4ce5-8d30-b618565d537d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'M.Prev Quarter Label' =
			
			VAR prevIdx = [M.Selected Quarter Index] - 1
			RETURN
			CALCULATE (
			    MAX ( DimQuarter[quarter] ),
			    REMOVEFILTERS ( DimQuarter ),
			    KEEPFILTERS ( DimQuarter[QuarterIndex] = prevIdx )
			)
		lineageTag: db188f9b-5b77-4d58-86c7-ca4c181dea10

	measure 'M.Sales (QTD)' =
			
			COALESCE( SUM( dfiq_manager_summary[baseline_sales] ), 0 )
		lineageTag: 5cdab175-d49b-4966-8cbf-2b364707ce6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'M.Goals (QTD)' =
			
			COALESCE( SUM( dfiq_manager_summary[simulated_goals] ), 0 )
		lineageTag: 91d8f2ba-697a-423e-8a2c-1374b11b954e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'M.TotalCompDisbursed' =
			
			SUM ( 'dfiq_manager_summary'[tot_comp_dis] )
		lineageTag: 8a34f8da-36be-47f4-b393-9dfc1f158fa3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalCompensationDisbursedPrevQ = ```
			
			VAR CurrentQuarter = MAX(DimQuarter[QuarterIndex])
			VAR PrevQuarter = CurrentQuarter - 1
			RETURN
			    IF (
			        ISBLANK (
			            CALCULATE (
			                AVERAGE(dfiq_manager_summary[tot_comp_dis]),
			                DimQuarter[QuarterIndex] = PrevQuarter,
			                REMOVEFILTERS(DimQuarter[quarter]) 
			            )
			        ),
			        "N/A",  
			        CALCULATE (
			            AVERAGE(dfiq_manager_summary[tot_comp_dis]),
			            DimQuarter[QuarterIndex] = PrevQuarter,
			            REMOVEFILTERS(DimQuarter[quarter])  
			        )
			    )
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e625ed46-511c-4fbd-95b3-c1c43eee1b2c

	measure EmployeesWithPayout200PrevQ =
			
			VAR CurrentQuarter =
			    MAX ( DimQuarter[QuarterIndex] )
			VAR PrevQuarter =
			    CurrentQuarter - 1
			RETURN
			CALCULATE (
			    [EmployeesWithPayout200_CurrentQ],
			    REMOVEFILTERS ( DimQuarter[Quarter] ),
			    DimQuarter[QuarterIndex] = PrevQuarter
			)
		formatString: 0
		lineageTag: a0199d80-bf5d-40cf-b8d9-c06e11d769e7

	measure AvgAttainmentPrevQ =
			
			VAR CurrentQuarter = MAX(DimQuarter[QuarterIndex])
			VAR PrevQuarter = CurrentQuarter - 1
			RETURN
			    IF (
			        ISBLANK (
			            CALCULATE (
			                AVERAGE(dfiq_manager_summary[avg_att]),
			                DimQuarter[QuarterIndex] = PrevQuarter,
			                REMOVEFILTERS(DimQuarter[quarter])   -- Removing other filters
			            )
			        ),
			        "N/A",  -- Return "N/A" if no value exists for the previous quarter
			        CALCULATE (
			            AVERAGE(dfiq_manager_summary[avg_att]),
			            DimQuarter[QuarterIndex] = PrevQuarter,
			            REMOVEFILTERS(DimQuarter[quarter])   -- Removing other filters
			        )
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cdba4ea7-875b-4075-87d3-47a4e0e37060

	measure Bottom10AvgPayoutPrevQ =
			
			VAR CurrentQuarter = MAX(DimQuarter[QuarterIndex])
			VAR PrevQuarter = CurrentQuarter - 1
			RETURN
			    IF (
			        ISBLANK (
			            CALCULATE (
			                AVERAGE(dfiq_manager_summary[bot_10_avg_pay]),
			                DimQuarter[QuarterIndex] = PrevQuarter,
			                REMOVEFILTERS(DimQuarter[quarter])   -- Removing other filters
			            )
			        ),
			        "N/A",  -- Return "N/A" if no value exists for the previous quarter
			        CALCULATE (
			            AVERAGE(dfiq_manager_summary[bot_10_avg_pay]),
			            DimQuarter[QuarterIndex] = PrevQuarter,
			            REMOVEFILTERS(DimQuarter[quarter])   -- Removing other filters
			        )
			    )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e5166b93-ab72-4b9e-8f24-b9bf006abd32

	measure Top10AvgPayout_PrevQ =
			
			VAR CurrentQuarter = MAX(DimQuarter[QuarterIndex])
			VAR PrevQuarter = CurrentQuarter - 1
			RETURN
			    IF (
			        ISBLANK (
			            CALCULATE (
			                AVERAGE(dfiq_manager_summary[top_10_avg_pay]),
			                DimQuarter[QuarterIndex] = PrevQuarter,
			                REMOVEFILTERS(DimQuarter[quarter])   -- Removing other filters
			            )
			        ),
			        "N/A",  -- Return "N/A" if no value exists for the previous quarter
			        CALCULATE (
			            AVERAGE(dfiq_manager_summary[top_10_avg_pay]),
			            DimQuarter[QuarterIndex] = PrevQuarter,
			            REMOVEFILTERS(DimQuarter[quarter])   -- Removing other filters
			        )
			    )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: fe81ff2a-dfee-4c84-a935-06a44c0bf7e6

	measure 'Top 5 Value' =
			
			VAR TopRank =
			    MAX ( 'dfiq_manager_summary'[emp_rank_top10] )   -- 1 = best, 10 = 10th best
			RETURN
			IF (
			    NOT ISBLANK ( TopRank )
			        && TopRank <= 5,
			    [Earning %]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 346263fb-0771-4a05-abc8-25e985ae1303

	measure 'M.Avg Attainment %' =
			
			DIVIDE ( SUM ( dfiq_manager_summary[attainment] ), [M.Reps] )
		lineageTag: 01f996a6-c6f3-45d1-9e40-8c90bfd66d0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Bottom10AvgPayout_CurrentQ =
			
			AVERAGE ( 'dfiq_manager_summary'[bot_10_avg_pay] )
		lineageTag: 8a6a0092-82ed-4abc-9378-e7362cb22e99

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Top10AvgPayout_CurrentQ =
			
			AVERAGE ( 'dfiq_manager_summary'[top_10_avg_pay] )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f31fb98d-8aff-4919-8b76-7e40e18ec954

	measure TotalCompensationDisbursed_CurrentQ =
			
			AVERAGE ( dfiq_manager_summary[tot_comp_dis] )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ab2eb978-a441-4c59-a312-2ae628bbae13

	measure TotalCompensationDisbursedPrevQ_Label =
			
			VAR PrevQ = [TotalCompensationDisbursedPrevQ]
			RETURN
			IF (
			    ISBLANK ( PrevQ ),
			    "-",
			    FORMAT ( PrevQ, "$#,0" )
			)
		lineageTag: 7e1908f4-5691-47e0-ba74-7390db3334e6

	measure EmployeesWithPayout200_CurrentQ =
			
			AVERAGE ( dfiq_manager_summary[mt_200] )
		formatString: 0
		lineageTag: 040face0-1846-4d53-b077-3c1885836c74

	measure EmployeesWithPayout200PrevQ_Label =
			
			VAR PrevQ = [EmployeesWithPayout200PrevQ]
			RETURN
			IF (
			    ISBLANK ( PrevQ ),
			    "N/A",
			    FORMAT ( PrevQ, "#,0" )
			)
		lineageTag: 6402b48f-4aec-460f-bb27-2140ee4ad696

	measure AvgAttainment%_PrevQ =
			VAR CurrentQuarter =
			    MAX ( DimQuarter[QuarterIndex] )
			VAR PrevQuarter =
			    CurrentQuarter - 1
			RETURN
			CALCULATE (
			    [M1.PresentQuarterAttainment],
			    REMOVEFILTERS ( DimQuarter[Quarter] ),
			    DimQuarter[QuarterIndex] = PrevQuarter
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 99aeec2c-d9b9-42bd-8900-3ce1156c56ad

	measure AvgAttainment%_CurrentQ = AVERAGE ( dfiq_manager_summary[avg_att] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f68bb5fd-4f37-4c52-bc95-91e763164394

	measure ChangeFromPreviousEarnings_Label = ```
			
			VAR d = [M3.ChangeFromPreviousEarnings]
			RETURN
			IF (
			    ISBLANK ( d ),
			    "–",                             
			    FORMAT ( d, "0.00%" )
			)
			```
		lineageTag: 88c67d76-71c4-4687-826e-615f61d52fb6

	measure 'M.IconColour.Earning' =
			
			VAR s = [M.Earnings_ChangeSign]
			RETURN
			SWITCH (
			    TRUE(),
			    ISBLANK ( s ), "#9CA3AF",      -- grey for “–”
			    s = -1,        "#DC2626",      -- red
			    s = 0,         "#2563EB",      -- blue
			                   "#16A34A"       -- green
			)
		lineageTag: c91a8a73-e529-44c4-a8a0-5cbbff505451

	measure 'M.Color.EarningsChange' =
			
			VAR s = [M.Earnings_ChangeSign]
			RETURN
			SWITCH (
			    TRUE(),
			    ISBLANK ( s ), "#9CA3AF",      -- grey for “–”
			    s = -1,        "#DC2626",      -- red
			    s = 0,         "#2563EB",      -- blue
			                   "#16A34A"       -- green
			)
		lineageTag: aa39ed6e-4c7d-47f0-b4a0-e590807fa0c5

	measure 'Latest Column' = 1
		formatString: 0
		lineageTag: b4bdecff-c314-4210-a7b7-d886daceb4b3

	column emp_name
		dataType: string
		lineageTag: 141f7e44-4f7b-4353-a516-f894c0eed955
		summarizeBy: none
		sourceColumn: emp_name

		annotation SummarizationSetBy = Automatic

	column eligibility
		dataType: double
		lineageTag: 47f65934-ed4c-4f0c-b14b-5835612cb484
		summarizeBy: sum
		sourceColumn: eligibility

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column brand
		dataType: string
		lineageTag: 95fb7cbc-35f5-4528-8ba5-d3884e83bffd
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column baseline_sales
		dataType: double
		formatString: 0
		lineageTag: 1a2b7b48-6f6c-4710-8d3b-8cc3bb643804
		summarizeBy: sum
		sourceColumn: baseline_sales

		annotation SummarizationSetBy = Automatic

	column simulated_goals
		dataType: double
		formatString: 0
		lineageTag: 2898830a-6724-4964-8056-c6082abbee42
		summarizeBy: sum
		sourceColumn: simulated_goals

		annotation SummarizationSetBy = Automatic

	column attainment
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: db88421f-310b-424b-b5ce-ccc84a7736d3
		summarizeBy: sum
		sourceColumn: attainment

		annotation SummarizationSetBy = Automatic

	column target
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3888f069-5728-46a7-a87e-8727bad5a6a4
		summarizeBy: sum
		sourceColumn: target

		annotation SummarizationSetBy = Automatic

	column earning_percent
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 71550910-03ec-418d-a5d9-f3e61da1b4fb
		summarizeBy: average
		sourceColumn: earning_percent

		annotation SummarizationSetBy = User

	column quarter
		dataType: string
		lineageTag: 8d89f574-70ed-48a2-96df-5afab6bc7d08
		summarizeBy: none
		sourceColumn: quarter

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column post_eligibility_earnings
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2ed8e283-89f5-4915-9d2f-893cfc26bd4b
		summarizeBy: sum
		sourceColumn: post_eligibility_earnings

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column team_name
		dataType: string
		lineageTag: b5913cfd-2a8b-42ca-8477-cea4f3549859
		summarizeBy: none
		sourceColumn: team_name

		annotation SummarizationSetBy = Automatic

	column refresh_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b8554e2c-742a-490a-b9fc-706adc592c6b
		summarizeBy: none
		sourceColumn: refresh_date

		variation Variation
			isDefault
			relationship: 294bc291-6c6e-4b48-854e-9b83be74fcfa
			defaultHierarchy: LocalDateTable_e446b31f-339b-4526-88b2-ab4e944e9014.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Reps ≥ 200%' =
			
			VAR _count =
			    CALCULATE(
			        DISTINCTCOUNT(dfiq_manager_summary[emp_id]),
			        dfIQ_manager_summary[earning_percent] >= 200
			    )
			RETURN
			COALESCE(_count, 0)
		formatString: 0
		lineageTag: a4a09a0f-6d1a-416c-89e4-5bbd75369066
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'M.Earning_Bucket' =
			
			SWITCH(
			    TRUE(),
			    'dfiq_manager_summary'[earning_percent] < 0.75, "<75%",
			    'dfiq_manager_summary'[earning_percent] >= 0.75 && 'dfiq_manager_summary'[earning_percent] < 1, "75% - 100%",
			    'dfiq_manager_summary'[earning_percent] >= 1 && 'dfiq_manager_summary'[earning_percent] < 1.25, "100% - 125%",
			    'dfiq_manager_summary'[earning_percent] >= 1.25 && 'dfiq_manager_summary'[earning_percent] < 1.5, "125% - 150%",
			    'dfiq_manager_summary'[earning_percent] >= 1.5, ">150%",
			    "Others"
			)
		lineageTag: 4034bf5b-5dbf-4097-b7a0-cdeef696f417
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'M.Earning_Bucket_Order' = ```
			
			SWITCH(
			    TRUE(),
			    'dfiq_manager_summary'[earning_percent] < 0.75, 1,
			    'dfiq_manager_summary'[earning_percent] >= 0.75 && 'dfiq_manager_summary'[earning_percent] < 1, 2,
			    'dfiq_manager_summary'[earning_percent] >= 1 && 'dfiq_manager_summary'[earning_percent] < 1.25, 3,
			    'dfiq_manager_summary'[earning_percent] >= 1.25 && 'dfiq_manager_summary'[earning_percent] < 1.5, 4,
			    'dfiq_manager_summary'[earning_percent] >= 1.5, 5,
			    6
			)   
			```
		formatString: 0
		lineageTag: b0be33e9-ab63-487d-b3c7-a2d002ad93c0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'M.AvgAtt_Bucket' =
			
			SWITCH(
			    TRUE(),
			    [M.AvgAtt%_PerEmployee] < 0.75, "> 75%",
			    [M.AvgAtt%_PerEmployee] >= 0.75 && [M.AvgAtt%_PerEmployee] < 1, "75% - 100%",
			    [M.AvgAtt%_PerEmployee] >= 1 && [M.AvgAtt%_PerEmployee] < 1.25, "100% - 125%",
			    [M.AvgAtt%_PerEmployee] >= 1.25 && [M.AvgAtt%_PerEmployee] < 1.5, "125% - 150%",
			    [M.AvgAtt%_PerEmployee] >= 1.5, ">150%",
			    "Other"
			)
		lineageTag: 7af7a586-1969-44d9-b55f-15570dc234b8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'M.AvgAtt_Bucket_Order' =
			
			SWITCH(
			    TRUE(),
			    [M.AvgAtt%_PerEmployee] < 0.75, 1,
			    [M.AvgAtt%_PerEmployee] >= 0.75 && [M.AvgAtt%_PerEmployee] < 1, 2,
			    [M.AvgAtt%_PerEmployee] >= 1 && [M.AvgAtt%_PerEmployee] < 1.25, 3,
			    [M.AvgAtt%_PerEmployee] >= 1.25 && [M.AvgAtt%_PerEmployee] < 1.5, 4,
			    [M.AvgAtt%_PerEmployee] >= 1.5, 5,
			    6
			)
		lineageTag: 53edfe2f-c6b0-4c13-9196-45f2df58d943
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'M.AvgAtt%' = AVERAGE(dfiq_manager_summary[attainment])/COUNT(dfiq_manager_summary[emp_id])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ffee89a6-b3cc-4067-bc13-ea146c2615cf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'M.AvgAtt%_PerEmployee' = ```
			
			CALCULATE(
			    AVERAGE(dfiq_manager_summary[attainment]),
			    ALLEXCEPT(dfiq_manager_summary, dfiq_manager_summary[emp_id])
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d913705a-2ca4-4144-b897-4c027bc37c77
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column territory_name
		dataType: string
		lineageTag: 8b388fbb-a774-4b15-8213-ee26bf80d7a3
		summarizeBy: none
		sourceColumn: territory_name

		annotation SummarizationSetBy = Automatic

	column terr_id
		dataType: string
		lineageTag: 34a54546-43c1-4e57-8e39-0b8e02295c26
		summarizeBy: none
		sourceColumn: terr_id

		annotation SummarizationSetBy = Automatic

	column manager_name
		dataType: string
		lineageTag: a0ee32b2-6a65-4cc1-a0b0-1d166d170307
		summarizeBy: none
		sourceColumn: manager_name

		annotation SummarizationSetBy = Automatic

	column mgr_terr_name
		dataType: string
		lineageTag: 066ab9e3-82cb-49b1-a253-3675f669fabe
		summarizeBy: none
		sourceColumn: mgr_terr_name

		annotation SummarizationSetBy = Automatic

	column mgr_terr_id
		dataType: string
		lineageTag: 92ace25a-62dc-4905-b22c-880dda9ab7d6
		summarizeBy: none
		sourceColumn: mgr_terr_id

		annotation SummarizationSetBy = Automatic

	column mgr_emp_id
		dataType: string
		lineageTag: a9ea4ec5-086c-4f5c-9f3c-9c9c97b05810
		summarizeBy: none
		sourceColumn: mgr_emp_id

		annotation SummarizationSetBy = Automatic

	column mgr_target_pay
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: a63a0467-64da-494e-946b-bb0631b01a12
		summarizeBy: sum
		sourceColumn: mgr_target_pay

		annotation SummarizationSetBy = Automatic

	column mgr_terr_rank
		dataType: int64
		formatString: 0
		lineageTag: 1dc8e7ae-e2f5-4a4c-ae4b-a7fd6c95059a
		summarizeBy: sum
		sourceColumn: mgr_terr_rank

		annotation SummarizationSetBy = Automatic

	column 'M.Selected Quarter Index (Safe)' =
			
			VAR idx = MAX ( 'DimQuarter'[QuarterIndex] )
			RETURN IF ( NOT ISBLANK ( idx ), idx,
			            CALCULATE ( MAX ( 'DimQuarter'[QuarterIndex] ), ALL ( 'DimQuarter' ) ) )
		lineageTag: d12bbce6-0945-46f1-92aa-18c26f50afa3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mgr_email_id
		dataType: string
		lineageTag: 0134bdae-3848-4a85-bbca-8e1ffa6bf19d
		summarizeBy: none
		sourceColumn: mgr_email_id

		annotation SummarizationSetBy = Automatic

	column emp_rank_top10
		dataType: int64
		formatString: 0
		lineageTag: 5b007aaa-3db7-445c-b8b3-44784b70157d
		summarizeBy: sum
		sourceColumn: emp_rank_top10

		annotation SummarizationSetBy = Automatic

	column emp_rank_bottom10
		dataType: int64
		formatString: 0
		lineageTag: 3ab26b4d-24c9-462b-a1ed-85cca3437588
		summarizeBy: sum
		sourceColumn: emp_rank_bottom10

		annotation SummarizationSetBy = Automatic

	column tot_comp_dis
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 74dbe294-6eaa-4279-aef9-0fd7e9159385
		summarizeBy: sum
		sourceColumn: tot_comp_dis

		annotation SummarizationSetBy = Automatic

	column mt_200
		dataType: int64
		formatString: 0
		lineageTag: 53e965ab-87f8-4f36-ad46-308142282efd
		summarizeBy: sum
		sourceColumn: mt_200

		annotation SummarizationSetBy = Automatic

	column avg_att
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 302e3567-b8c8-4fd9-a421-0eddb34c329f
		summarizeBy: sum
		sourceColumn: avg_att

		annotation SummarizationSetBy = Automatic

	column top_10_avg_pay
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 580013b5-1312-44e1-9b20-624ca76c0bf1
		summarizeBy: sum
		sourceColumn: top_10_avg_pay

		annotation SummarizationSetBy = Automatic

	column bot_10_avg_pay
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d78c3234-a148-4458-a782-b9c441a71e23
		summarizeBy: sum
		sourceColumn: bot_10_avg_pay

		annotation SummarizationSetBy = Automatic

	column engagement_rate
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d6acfa06-a559-4549-ab40-586e0ae19665
		summarizeBy: sum
		sourceColumn: engagement_rate

		annotation SummarizationSetBy = Automatic

	column meaningful_engagement
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e2ce3d60-a42c-4a2e-aea2-530068b2ec21
		summarizeBy: sum
		sourceColumn: meaningful_engagement

		annotation SummarizationSetBy = Automatic

	column performance_kpi
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b496582d-803a-4229-b063-f5633bc3d232
		summarizeBy: sum
		sourceColumn: performance_kpi

		annotation SummarizationSetBy = Automatic

	column budget_utilization
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 206fb7bf-0d8c-44a6-aa1b-6997ee6d8791
		summarizeBy: sum
		sourceColumn: budget_utilization

		annotation SummarizationSetBy = Automatic

	column avg_achievement
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f0769add-6356-4dad-8719-5495fa122472
		summarizeBy: sum
		sourceColumn: avg_achievement

		annotation SummarizationSetBy = Automatic

	column emp_id
		dataType: string
		lineageTag: 00a94148-68a3-4652-ae03-880ad6778de9
		summarizeBy: none
		sourceColumn: emp_id

		annotation SummarizationSetBy = Automatic

	column Column
		type: calculated
		lineageTag: 1c4780d4-b040-4dbf-9a5e-ea4f3bc1d674
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	column mgr_emp_role
		dataType: string
		lineageTag: d84cf755-a2e7-4785-b6c8-3d3c3d9f27f2
		summarizeBy: none
		sourceColumn: mgr_emp_role

		annotation SummarizationSetBy = Automatic

	partition dfiq_manager_summary = m
		mode: import
		source =
				let
				    Source = AmazonAthena.Databases("AmazonAthena", null, []),
				    AwsDataCatalog_Database = Source{[Name="AwsDataCatalog",Kind="Database"]}[Data],
				    dfiq_normalized_Schema = AwsDataCatalog_Database{[Name="dfiq_normalized",Kind="Schema"]}[Data],
				    dfiq_manager_summary_Table = dfiq_normalized_Schema{[Name="dfiq_manager_summary",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dfiq_manager_summary_Table,{{"mgr_name", "manager_name"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

