table 'KPI Def'
	lineageTag: bd2ccf18-44e3-4b7c-8c11-3d7bbe6995aa

	column 'Metric Name'
		dataType: string
		lineageTag: 962426a8-e5f3-4178-862c-6d48dca9d5ed
		summarizeBy: none
		sourceColumn: Metric Name

		annotation SummarizationSetBy = Automatic

	column 'Metric Definition'
		dataType: string
		lineageTag: 7609a49f-f6c8-465a-ad09-fd181228206f
		summarizeBy: none
		sourceColumn: Metric Definition

		annotation SummarizationSetBy = Automatic

	partition 'KPI Def' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dZDBagMxDER/Rfgc+g8lPffQ65KD45U3Als2ktyQv6+chTaB9GCwxczTeJYlfOFGahKNGms4hM9RzyjQMnSfIZv6PVOiWMoNkKWVgisQg11wHon9Bl3aJrG+hdNhCe/dp6j0D+56aZBa7QXNQQlL8adD04wAuckvtUYeOSYbQrzt7A8s9I1C+Az/Uzpyt7sEdKSEqnnM7OtunYIGJhiteh4PwIaiO/4YeQZ60Ybce7rbH3+iTx3MZXCNCitpamzEA1cnn34A", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Metric Name" = _t, #"Metric Definition" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric Name", type text}, {"Metric Definition", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

