table 'Measures - All Screen'
	lineageTag: 0be3159f-4cff-41ff-a863-b66706998bdc

	measure 'Refresh Date' = "Report Refresh Date : 8-Jan-2026"
		lineageTag: f9809d63-2106-484c-a7df-4d799eb50b51

	measure Registrations = 12450
		formatString: #,0
		lineageTag: 9e2ab881-ebeb-4dfb-9817-bf81836aa53b

	measure 'Registrations Goal' = 14000
		formatString: #,0
		lineageTag: a3cf6f94-daf3-4599-9b95-94e540b22bd7

	measure 'Registrations Growth' = 0.02
		formatString: 0%;-0%;0%
		lineageTag: 9a34d4cc-af75-442e-9e17-8196ce9164ed

	measure Apheresis = 11000
		formatString: #,0
		lineageTag: 8be52423-492f-4d9d-a3cf-649990b10da6

	measure 'Apheresis Goal' = 10000
		formatString: #,0
		lineageTag: 01a6f756-0dd3-4167-b6ae-2884eafe36b4

	measure 'Apheresis Growth' = 0.322
		formatString: 0%;-0%;0%
		lineageTag: 44611ccc-e10b-4669-8fe6-65fb3958e36f

	measure Deliveries = 1450
		formatString: #,0
		lineageTag: 65d99c32-56b7-4b59-9165-7d54b62007cd

	measure 'Deliveries Goal' = 1500
		formatString: #,0
		lineageTag: b6d84453-fb7d-4460-a205-c091ed9cdd8d

	measure 'Deliveries Growth' = 0.96
		formatString: 0%;-0%;0%
		lineageTag: 64761920-d89a-419a-a939-bcb36975111d

	measure Cancellations = 200
		formatString: 0
		lineageTag: eceee041-63e0-4e43-af45-9c00d3adbda6

	measure 'Cancellation Rate' = 0.041
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: ab2a9994-0c31-4f51-b92d-ee686aa241a4

	measure 'Cancellation Growth' = 0.236
		formatString: 0%;-0%;0%
		lineageTag: 9a4ddbfe-626d-45bc-ade1-b1b29b40b1b0

	measure 'Total ATCs' = 4730
		formatString: #,0
		lineageTag: 22b10f97-5857-47f8-96ad-e780c793e06c

	measure 'Total ATCs growth' = 0.08
		formatString: 0%;-0%;0%
		lineageTag: c864a473-f46f-4220-b0c8-7c2d382f0dfb

	measure 'Total HCPs' = 12470
		formatString: #,0
		lineageTag: c8260d29-1fb6-4581-96ed-29f62888a342

	measure 'New HCPs' = 2000
		formatString: #,0
		lineageTag: aa245f04-7f7b-4449-bad1-15352c702243

	measure 'New HCPs growth' = 0.06
		formatString: 0%;-0%;0%
		lineageTag: e5f0c310-84dc-4e47-9430-5c60d27412ed

	measure 'Total ATCs New' = 550
		formatString: 0
		lineageTag: 8872b8df-fe37-4a2b-8cdf-8ee557b30d1a

	measure 'Total ATCs Activated' = 425
		formatString: 0
		lineageTag: d49acfbb-981f-4636-a114-c4e82e2b50b0

	measure 'Pre Call Card Note:' = ```
			REPT(UNICHAR(160),12) & "Only 2,603 more registrations needed to reach the goal of this YTD." 
			```
		lineageTag: 43e934c8-6731-4d6a-a658-bbdca41cf874

	measure 'Fake Data' = RANDBETWEEN(10,200)
		formatString: 0
		lineageTag: fd78e094-6dcf-494b-8034-c075f69bc13a

	measure 'Total Calls' = 1551
		formatString: #,0
		lineageTag: 2b418dea-840f-4021-8917-fcab9c7dea3d

	measure 'Target Calls %' = 0.599
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 229fe6ce-0770-4315-af91-5a46c48deb30

	measure 'Nation Avg.' = 1800.1
		formatString: #,0.0
		lineageTag: 332c4225-a85c-4f36-bb91-86f5c82470ea

	measure Frequency = 5.22
		lineageTag: adb56343-231e-4fd9-ba4b-c59f74c44d7f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Frequency Goal' = 5.00
		formatString: 0.0
		lineageTag: 8706033d-5c2c-40b3-a4ce-a068f21cbe78

	measure 'Target Reach' = 0.631
		formatString: 0%;-0%;0%
		lineageTag: abebfc5b-5f48-4e8b-a54c-b6130655ff69

	measure 'Reach Goal' = 0.85
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 86b16a5b-2402-4af0-95c8-d8d362592d94

	measure 'In-Person Calls' = 951
		formatString: 0
		lineageTag: a56707cd-5a7f-471a-ba98-95a1bd1cde7e

	measure 'Virtual Calls' = [Total Calls] - [In-Person Calls]
		formatString: #,0
		lineageTag: 3d07338f-9217-4b21-be61-17ac44d9be7e

	measure 'Avg Calls per Day' = 8.09
		formatString: 0.0
		lineageTag: fe31bfe7-9508-4604-80b2-0baa050944c1

	measure 'Calls Nation Avg.' = 5.06
		lineageTag: 5d7703f0-2889-4199-9954-9801fb37dce2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Activity Note:' = ```
			REPT(UNICHAR(160),12) & "Only 1,275 more calls needed to reach the goal of this YTD." 
			```
		lineageTag: 6ce3dc5a-97cd-48c8-afa0-efa2d7e9b552

	measure 'Target Calls' = 1126
		formatString: #,0
		lineageTag: 6aabde3b-b668-4c60-9bcb-8270652aa533

	measure 'Apheresis Growth Abs' = -0.322
		lineageTag: d40e2c1b-01a5-4b50-80c2-781bc3782a99

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected KPI' = SELECTEDVALUE('Performance KPI Table'[KPIs])
		lineageTag: 1cd25b3e-5d1d-4bf2-bc28-77ee330985c7

	measure 'Attainment %' = ```
			
			IF(SELECTEDVALUE('Performance KPI Table'[KPIs]) in {"Registrations", "Apheresis", "Deliveries"}, 
			RAND(), BLANK())
			```
		lineageTag: f6e839bb-2ef1-4015-995d-b00f954b9c5b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Open = 800
		formatString: 0
		lineageTag: f9f63f7f-110f-4f00-9014-fd76a7a0d4a6

	measure Clicked = 177
		formatString: 0
		lineageTag: f872b01a-d46f-4c8d-8b1b-6b56babf8748

	measure 'Total Referrals' = 25
		formatString: 0
		lineageTag: 56593b1b-a835-4662-8fe7-4930efd9439c

	measure 'Non ATC to ATC Referrals' = 18
		formatString: 0
		lineageTag: adf845c2-cd07-43cb-9633-9a4004db91ee

	measure TEST =
			
			SWITCH(SELECTEDVALUE('Performance KPI Table'[KPIs]),
			"Registrations", 12350,
			"Apheresis", 11000,
			"Deliveries", 1450,
			"Cancellations", 200
			)
		formatString: #,0
		lineageTag: 46580d6f-67c7-445d-a406-8c201ec02eed

	measure Rand = RANDBETWEEN(100,500)
		lineageTag: f6de2420-247b-4b23-aa03-82fe3ceaa1cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Market Share' =
			
			RAND()
		formatString: 0%;-0%;0%
		lineageTag: dff996fa-a5af-4f6f-8af0-7f4796dee2b5

	measure 'Last Apheresis Date' = "2026-01-12"
		lineageTag: ab810108-49d2-4c9a-8103-c100f1294fbf

	measure 'Registration Attainment' = DIVIDE([Registrations],[Registrations Goal],0)
		formatString: 0%;-0%;0%
		lineageTag: 853a709c-86a4-4b5b-8632-22fbbb243d53

	measure 'Pending Registration Attainment' = DIVIDE(ABS([Registrations]-[Registrations Goal]),[Registrations Goal],0)
		lineageTag: 92f0688c-f18a-4555-a325-af79fcc04ba6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Target Attainment' = DIVIDE(8000,12450,0)
		formatString: 0%;-0%;0%
		lineageTag: 3e255ed0-429c-4578-a635-8a181e14b6c9

	measure 'Last Call Date' = "2026-01-19"
		lineageTag: 71820a3d-7d9b-46d1-adde-38506db55af5

	measure Patients = RANDBETWEEN(1,5)
		formatString: 0
		lineageTag: 3513b47b-7dfe-4c83-94c4-80f8410d6fe1

	measure '102 %' = 1.06
		formatString: 0%;-0%;0%
		lineageTag: 537a0313-59cd-4821-ac7b-2edfb12cfdb7

	measure 'Pending Deliveries' = 0.04
		formatString: 0%;-0%;0%
		lineageTag: 25ac4144-7bb4-4240-8298-810386556651

	measure 'Registartion Rand' = RANDBETWEEN(100,500)
		formatString: 0
		lineageTag: a07a63a5-de66-4300-9cea-1d5acd7b0bc9

	measure ATC_InfoBoxShowHide = ```
			
			    var _val = COUNTROWS('US_ATC_Mock_Data')
			    var _res = if(_val > 1, "#FBF9FF", "#FFFFFF00")
			    return _res
			```
		lineageTag: ebc43dc4-945b-4ad8-89a9-0adcf688c5a2

	measure 'ATC_InfoBoxText - ATC Information' = ```
			
			    var _val = COUNTROWS('US_ATC_Mock_Data')
			    var _res = if(_val > 1, "Click any location pointer on the map to see detailed ATC information.","")
			    return _res
			```
		lineageTag: 160ef77b-4c96-4193-b84a-568a7ed3af50

	measure 'ATC_InfoBoxText - HCP Information' = ```
			
			    var _val = COUNTROWS('US_ATC_Mock_Data')
			    var _res = if(_val > 1, "Click any location pointer on the map to see detailed HCP List.","")
			    return _res
			```
		lineageTag: 28dd9e77-a938-45a8-9934-da49088dce6b

	measure 'Attainment % showHide' = ```
			
			IF(SELECTEDVALUE('Performance KPI Table'[KPIs]) in {"Registrations", "Apheresis", "Deliveries"}, 
			"#FFFFFF00", "#FFFFFF")
			```
		lineageTag: 82b42124-038f-4a20-ab5a-c8e41d9d0141

	column Column1 = "Nation"
		lineageTag: ce28a5d7-b332-4ee8-ab04-ef256d5b625e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Measures - All Screen' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

