table 'Refresh Date'
	lineageTag: 6a99b5e7-815e-4e11-b3ff-b225d20d220c

	column 'Data Source Name'
		dataType: string
		lineageTag: 95bf615a-8188-421c-90b5-2382b3384a98
		summarizeBy: none
		sourceColumn: Data Source Name

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 7fe99d7a-7fc7-4353-b3e3-7cc437d10522
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column 'Data as of Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 98ca14f9-8c0c-4cbf-90aa-4ef5d4657269
		summarizeBy: none
		sourceColumn: Data as of Date

		variation Variation
			isDefault
			relationship: e011ab1f-fd34-4bfe-9d96-23c9eab2342f
			defaultHierarchy: LocalDateTable_743f3879-c5e6-45a9-8261-9f3e655d59c6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition 'Refresh Date' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8s4sSVXwzs/LS00uUdJRCk7MSS1W8MxLyy/KTSzJzM8DihkZGJnpGhjqGloqxepEK4WlppYlAoUdk0syyzJLKtFUxAIA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Data Source Name" = _t, Description = _t, #"Data as of Date" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Data Source Name", type text}, {"Description", type text}, {"Data as of Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

