table States
	lineageTag: 633b7e42-4934-4411-ac8e-f7450d8d81a6

	column 'State Code'
		dataType: string
		lineageTag: 489faf24-d8af-48ec-b263-4b1980f0a82f
		summarizeBy: none
		sourceColumn: State Code

		annotation SummarizationSetBy = Automatic

	column 'State Name'
		dataType: string
		lineageTag: 49f54486-9f60-4412-a3f8-b911e001d36b
		summarizeBy: none
		sourceColumn: State Name

		annotation SummarizationSetBy = Automatic

	column ID = RANDBETWEEN(1,51)
		formatString: 0
		lineageTag: 3c97095a-8323-4a46-abf1-0edb73c3313a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition States = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("XZPRbqMwEEV/BeW5PxHBtqEJUIU0bLbqwwTcMAI8kW2aZr9+PR4nu12Jl3tkX+5chre3xXKzeFgsRzjCBIv3Bw/WAuwQ9S/WBn+TjmAbwADagg0kXXqSwogfZDTKqbRiRiMZ6EjILhCtVeuwnV2A2Q8PMzXCBYwK5JEDPfp72InTE7s/KTKnaL3KPVj5G4hB55nXeQe9vCdng3wcURNKvrxkojuEOELOljldRK1rr9Z/x1kfWCvt5na4BrLh8xua0d4tCg5eAGpJXWRBmusIuhOyDMRaaPvZKufEvODwBbY9nkALKQPxvVhy0bwOyFp+zmcZs6gipNlEwo0WpN0tVMmhSnU0969X7gP5hFhmuQr6kqxgOtseY+nlc8TPylglQ5dFZIX6wla6LQ+RHcgMQlImZFyfpGDItx5flN15BsNtsIpfX/UobhWvWjWM/svF5at4tyqjTiTdvHCJL0prex0/4bZbW+5w21OnktzeC685SU3z/0nq7M7/SbLj1neKW7dKStj9DOgrrsErt/vqoA9qz2qvzOTrFsDR9ui38harYdKAb1WfXByg4f4bZV3y/ShP0KBtSVuMJ7na5kqTvy2/Bs+ToXUGW5fQR+L/pnk6ssP7Hw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"State Code" = _t, #"State Name" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"State Code", type text}, {"State Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

