table 'Time Bucket Def'
	lineageTag: 080fa901-860c-42b0-8be5-aafa0118e8f1

	column 'Time Period Abbreviation'
		dataType: string
		lineageTag: 989bf4c8-6198-4256-8403-d86808864398
		summarizeBy: none
		sourceColumn: Time Period Abbreviation

		annotation SummarizationSetBy = Automatic

	column 'Time Period'
		dataType: string
		lineageTag: d7e74471-35e7-49fb-b4bb-92af42542a0f
		summarizeBy: none
		sourceColumn: Time Period

		annotation SummarizationSetBy = Automatic

	column 'Current Start Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 960849cd-d502-41ba-83fa-1b4f76722661
		summarizeBy: none
		sourceColumn: Current Start Date

		variation Variation
			isDefault
			relationship: 993b1ce9-31b9-4f00-a415-689b19d5b025
			defaultHierarchy: LocalDateTable_90276fdf-b385-452a-b05e-742845f5d479.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Current End Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: cdd35871-2959-4bd8-bcef-de3d2c1305b3
		summarizeBy: none
		sourceColumn: Current End Date

		variation Variation
			isDefault
			relationship: d0e7035b-7c69-424f-8a4d-346d4e9cbfad
			defaultHierarchy: LocalDateTable_f360f96f-18f0-47fd-b929-f5d545ebbb29.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Previous Start Date'
		dataType: string
		lineageTag: c41106f3-0fcb-4f5b-8e21-94a554cdd794
		summarizeBy: none
		sourceColumn: Previous Start Date

		annotation SummarizationSetBy = Automatic

	column 'Previous End Date'
		dataType: string
		lineageTag: cdf7f088-dd8a-4398-87fd-803036258867
		summarizeBy: none
		sourceColumn: Previous End Date

		annotation SummarizationSetBy = Automatic

	partition 'Time Bucket Def' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZDLDoMgEEV/hbC24WXFLomStilqRIwx1s/o/xfHGmh10d3lBs4cZppwMeAEF721unZo0Prhj4ySM+GUp2vOtnwhPI/yZc1zMmHjSt8Z1dfFDbkGlcrp5TFh/g7LfzjPF6VcnqK0MCpgVE3tvhAUGAcuLMQsmLRAaXtlnbZ/cGSoZcyxjFe+s40x9/qKGEdg1kUoAbMFjbDQ86gXH5gYYpiATXfreHGklUa9JDJ4jfC/USu72/MOwoLnVnuf+Q0=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Time Period Abbreviation" = _t, #"Time Period" = _t, #"Current Start Date" = _t, #"Current End Date" = _t, #"Previous Start Date" = _t, #"Previous End Date" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Time Period Abbreviation", type text}, {"Time Period", type text}, {"Current Start Date", type date}, {"Current End Date", type date}, {"Previous Start Date", type text}, {"Previous End Date", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

