table US_ATC_Mock_Data
	lineageTag: 9b3b910b-d8d1-4dc7-b486-e1311c0fa7eb

	measure 'Growth Measure' =
			
			IF(RAND() > 0.1 && RAND() < 0.5, RAND()*-1,RAND())
		formatString: 0%;-0%;0%
		lineageTag: 27b1a122-da81-4818-ae5d-28806ed0b2e0

	measure 'Delivery Successs rate' = "25%"
		lineageTag: b0621652-469f-4ede-a1ad-8f1113c100f5

	measure 'Dormant ATC Flag' = "Y"
		lineageTag: 1e74face-82fc-49e8-afd0-d651a8e11632

	measure 'Total RTEs' = RANDBETWEEN(10,20)
		formatString: 0
		lineageTag: 12e388d5-b52c-492a-8b78-c894bd4063ff

	measure 'ATC using outpatient' = "N"
		lineageTag: 706c232d-9ebe-49c5-bb3c-2203d3caf826

	measure 'Kite ATC' = "N"
		lineageTag: 96f86f69-97aa-48d6-a44c-59b63435cc32

	measure 'Abecma ATC' = "Y"
		lineageTag: 2f4a5913-67d9-498f-9056-92b3fc83e199

	measure 'Carvykti ATC' = "N"
		lineageTag: a27aa5c6-3da3-4a8e-81c7-0688e603fb0e

	measure 'MM Treated Patients 4L+' = RANDBETWEEN(1000,2000)
		formatString: #,0
		lineageTag: 1aee0355-592f-4cb5-a922-ab2cc3e2f718

	measure 'MM Treated Patients 2L+' = RANDBETWEEN(1000,2000)
		formatString: 0
		lineageTag: 99b3bd25-9b6f-4eaf-a39b-9b84c39cd70e

	measure 'All MM CAR-T Patient Volume' = RANDBETWEEN(1000,2000)
		formatString: 0
		lineageTag: f4ba9847-d274-45b3-ae5c-6feb2cb9fd56

	measure 'ATC Name MAP View' = "" & MAX('US_ATC_Mock_Data'[ATC Name])
		lineageTag: f166bc4b-1938-468f-8125-5d7b4815d61d

	measure 'ATC Address MAP View' = MAX('US_ATC_Mock_Data'[Address])
		lineageTag: 8c387b29-8752-4d41-a1d7-d3bc80836060

	measure 'Total HCPs MAP View' = "Total HCPs: " & DISTINCTCOUNT('US_ATC_Mock_Data'[Prescriber Name])
		lineageTag: df49e6c7-fc3e-4c6d-a60f-38b746f8e547

	measure 'HCP Priority' = "P2"
		lineageTag: 13a099de-8b59-4258-8440-937bba100717

	column 'ATC Name'
		dataType: string
		lineageTag: b7118ef8-57c2-4636-9040-43fb71fca895
		summarizeBy: none
		sourceColumn: ATC Name

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: 392dc2df-5906-434a-b9a0-57158bd3437d
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: b85c5f6e-6f24-426f-93b4-24cc3a9df458
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 2a0ce5f5-7285-4a3e-afa1-bb645fd99d66
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column ZIP
		dataType: int64
		formatString: 0
		lineageTag: b14a0c61-88f2-425b-aac3-d1e272c22bf5
		summarizeBy: sum
		sourceColumn: ZIP

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: 48bc9a5f-2da0-42c4-8e0b-fe3455314ef2
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column 'Account Segment'
		dataType: string
		lineageTag: b7e39a41-ec6b-45d8-8cba-3ad01bc45ed2
		summarizeBy: none
		sourceColumn: Account Segment
		sortByColumn: 'Segment Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Account Type'
		dataType: string
		lineageTag: 64ae71c0-1677-48a6-adf3-8e662834f273
		summarizeBy: none
		sourceColumn: Account Type

		annotation SummarizationSetBy = Automatic

	column 'Activated RTC Flag'
		dataType: string
		lineageTag: 216b9f3d-63fd-486d-856c-5885c6b901fa
		summarizeBy: none
		sourceColumn: Activated RTC Flag

		annotation SummarizationSetBy = Automatic

	column 'Target Flag'
		dataType: string
		lineageTag: f3a8d196-15e3-4f57-b1b3-415d3b7f465e
		summarizeBy: none
		sourceColumn: Target Flag

		annotation SummarizationSetBy = Automatic

	column 'Total Registrations'
		dataType: int64
		formatString: #,0
		lineageTag: 3b732d2c-e456-48cd-a08f-b555d080e86a
		summarizeBy: sum
		sourceColumn: Total Registrations

		annotation SummarizationSetBy = Automatic

	column 'Total Apheresis'
		dataType: int64
		formatString: 0
		lineageTag: 642d9e53-3935-47cd-840a-6e78487d053f
		summarizeBy: sum
		sourceColumn: Total Apheresis

		annotation SummarizationSetBy = Automatic

	column 'Total Cancellations'
		dataType: int64
		formatString: 0
		lineageTag: bf97f076-204d-4095-839d-fb407a45a3be
		summarizeBy: sum
		sourceColumn: Total Cancellations

		annotation SummarizationSetBy = Automatic

	column Tier =
			
			"Tier " & RANDBETWEEN(1,5)
		lineageTag: f00a2432-5098-4b26-8360-f49ff5f93d1e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Segment Sort'
		dataType: string
		lineageTag: ddeb7ee8-1e4c-491e-9ae8-591a0e585786
		summarizeBy: none
		sourceColumn: Segment Sort

		annotation SummarizationSetBy = Automatic

	column 'Prescriber Name'
		dataType: string
		lineageTag: 8ba52728-19b9-4801-a30e-b182302ae5df
		summarizeBy: none
		sourceColumn: Prescriber Name

		annotation SummarizationSetBy = Automatic

	column 'Prescriber Specialty'
		dataType: string
		lineageTag: d0c3b39e-00db-4298-8104-d3b7c1cd5237
		summarizeBy: none
		sourceColumn: Prescriber Specialty

		annotation SummarizationSetBy = Automatic

	column 'Prescriber Role'
		dataType: string
		lineageTag: e57d86d4-16c8-45b5-a19d-9d945bfedb87
		summarizeBy: none
		sourceColumn: Prescriber Role

		annotation SummarizationSetBy = Automatic

	column 'Prescriber NPI'
		dataType: string
		lineageTag: 0b6a7672-bc66-46a0-98b3-63bd02fb6a6d
		summarizeBy: none
		sourceColumn: Prescriber NPI

		annotation SummarizationSetBy = Automatic

	column ID = RANDBETWEEN(1,51)
		formatString: 0
		lineageTag: cfaad071-cc43-4132-9c92-cc2a25149216
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition US_ATC_Mock_Data = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\AK42909\Downloads\US_ATC_CAR_T_Mock_Data.xlsx"), null, true),
				    US_ATC_Mock_Data_Sheet = Source{[Item="US_ATC_Mock_Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(US_ATC_Mock_Data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ATC Name", type text}, {"Address", type text}, {"City", type text}, {"State", type text}, {"ZIP", Int64.Type}, {"Territory", type text}, {"Account Segment", type text}, {"Account Type", type text}, {"Activated RTC Flag", type text}, {"Target Flag", type text}, {"Total Registrations", Int64.Type}, {"Total Apheresis", Int64.Type}, {"Total Cancellations", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "Custom", each if [Account Segment] = "Gold" then 1 else if [Account Segment] = "Silver" then 2 else if [Account Segment] = "Bronze" then 3 else 4),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Conditional Column","Fred Hutch Cancer Center ATC","Stanford Health Care ATC",Replacer.ReplaceText,{"ATC Name"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","MD Anderson Cancer Center ATC","Stanford Health Care ATC",Replacer.ReplaceText,{"ATC Name"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value1",{{"Custom", "Segment Sort"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([State] <> "IL"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

