table '4 : KPI Glosaary'
	lineageTag: dde3931a-186b-445b-b5f9-d1ed1f6a2577

	column 'KPI Name'
		dataType: string
		lineageTag: e5e16565-b9dd-4520-b900-d36af150fb53
		summarizeBy: none
		sourceColumn: KPI Name
		sortByColumn: ID

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Definition
		dataType: string
		lineageTag: 6d8e0d1c-d32c-4d38-9814-a4de2991d700
		summarizeBy: none
		sourceColumn: Definition

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 4e1ffcb7-63b6-4868-9087-0eb71ae6f99c
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	partition '4 : KPI Glosaary' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("1ZZdb5swFIb/yhFXiUanNEu79ZJE026KNk1oN1kvHHMY1ozN/EHHv5/5CA3BaSM1UrWLSEkw53mP3+MXttsg2iEtCCQKicEUvhHDUBgdhMG1+yTSEA5xDGX/PzzmEnJSISikyCp3S1/B5KhIWcMjMzkTzU/QyJE2VQ0rEEpUTKZAqJJaA+EcOBOoQWb7e4OHcBtsiKrq34b5JC3PlDTUuJSo9SaOYK2jnfbJ+nCmrDXTJVKWMQqRMGwn07qnMNSzhPAK6xASpBWpOYOfdrFY3sJnrvBvxuT81V04dUfqYXn/zolfHTawbwxMv9YhNVIp0qumKsyW93OQCri7qJ70nyKsWsLNS4RMWmXynrA6TYh4W2ITfb9KBsYPyW2BDnHrcQKq9mpvAxO/gIi6L7Cfj1k3xOEwOWHDl83lbqWed/Ru1ifcj293VrpBnyj69FZH5QsKt5CecujuGYcyt+cTb0I3HZTbtDFu6hIR6cim9/sx7A7rBH+9+E/OakfwNHBuLPcFLmXr0OlU0bmpPJS4lKb9bns0nRvJQ4lLaRrl01drPNpWXm1P8TSOJuIQ1gzLDvjdulLJ1FKjD/PJz715gXsUTmPw+NnsB/jSd9TYcdZ4ENMnSPsu0gas88S05YUtdu7Iu623gv2xCLHlhpXcfamRS9fELI7nz/nePnmKRn5qVaPtlOHh4Y6TijBOdo4zRIELnId/", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"KPI Name" = _t, ID = _t, Definition = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"KPI Name", type text}, {"Definition", type text}, {"ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

