table 'Calculation Group'
	lineageTag: b8bc5f25-2918-469c-8a5a-4d0f081f37d9

	measure ATC_AbecmaTreatedPatient = SUM('1 : Account Universe - ATC Data'[ABECMA PATIENT VOLUME]) + 0
		formatString: #,0
		displayFolder: ATC Map Measures
		lineageTag: 98fdb1ed-f218-4f03-8d66-05ab37df0f91

	measure ATC_CarvyktiTreatedPatient = SUM('1 : Account Universe - ATC Data'[CARVYKTI PATIENT VOLUME]) + 0
		formatString: #,0
		displayFolder: ATC Map Measures
		lineageTag: 88ac9d82-ac11-42c9-b761-3a388ff6929f

	measure ATC_BCMABsAbsTreatedPatient = SUM('1 : Account Universe - ATC Data'[MM BsAbs Patient Volume]) + 0
		formatString: #,0
		displayFolder: ATC Map Measures
		lineageTag: 081ed5ae-7007-4253-bf40-5ee3066befa4

	measure ATC_InfoBoxShowHide = ```
			
			    var _val = COUNTROWS('1 : Account Universe - ATC Data')
			    var _res = if(_val > 1, "#F7F7F9", "#FFFFFF00")
			    return _res
			```
		displayFolder: ATC Map Measures
		lineageTag: adba99f9-add6-4546-8f43-db933b722be3

	measure ATC_MessageNoteShowHide = ```
			
			    var _val = COUNTROWS('1 : Account Universe - ATC Data')
			    var _res = if(_val > 1, "#FFFFFF00", "#FFFFFF")
			    return _res
			```
		displayFolder: ATC Map Measures
		lineageTag: dfd71c7e-ef0c-4b63-8c82-ba360d988d47

	measure CustList_MMTreatedPatients4L+ = SUM('2 : HCP Universe Data'[MM Treated Patient 4L+]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: 8bcd306f-a119-431f-9302-6bbb678c376a

	measure CustList_MMTreatedPatients2L+ = SUM('2 : HCP Universe Data'[MM Treated Patient 2L+]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: e54ef668-39df-44aa-b7bf-38ffd74a7161

	measure CustList_AllMMCAR-TPatientVolume = SUM('2 : HCP Universe Data'[All MM CAR T PATIENT VOLUME]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: 3fd63f7f-2560-4d3c-9648-e2f50b48e575

	measure CustList_ABECMAPatientVolume = SUM('2 : HCP Universe Data'[ABECMA PATIENT VOLUME]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: 9da171c6-d8a1-4a5a-ac7f-b6136ea891e9

	measure CustList_CARVYKTIPatientVolume = SUM('2 : HCP Universe Data'[CARVYKTI PATIENT VOLUME]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: 1625bdca-4419-426f-9dd0-5c4e61e0e507

	measure CustList_GenericCAR-TPatientVolume = SUM('2 : HCP Universe Data'[GENERIC CAR T PATIENT VOLUME]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: c5b1d0b8-89e5-4eea-93af-61ff6f1ff90f

	measure CustList_MMBsAbsPatientVolume = SUM('2 : HCP Universe Data'[MM BsAbs Patient Volume]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: 71813b78-122c-4343-917a-1c72fe724815

	measure CustList_TALVEYPatientVolume = SUM('2 : HCP Universe Data'[TALVEY Patient Volume]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: 0c932a07-e7e2-4928-96c0-8b33818f14b2

	measure CustList_TECVAYLIPatientVolume = SUM('2 : HCP Universe Data'[TECVAYLI Patient Volume]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: 6deceaa1-66b3-4248-b2c6-5fb02d2a9857

	measure CustList_ELREXFIOPatientVolume = SUM('2 : HCP Universe Data'[ELREXFIO Patient Volume]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: 7222dfc1-b44d-489d-b392-1b96b996b025

	measure CustList_AllMMCAR-TOPPatientVolume = SUM('2 : HCP Universe Data'[All MM CAR T OP PATIENT VOLUME]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: 81451cb5-2a2a-4052-9ed4-a532eb9e8706

	measure CustList_AllMMCARVYKTIOPPatientVolume = SUM('2 : HCP Universe Data'[CARVYKTI OUT PATIENT VOLUME]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: 58752e5d-f7e5-407b-b012-088eeaebc35e

	measure CustList_AllMMABECMAOPPatientVolume = SUM('2 : HCP Universe Data'[ABECMA OUT PATIENT VOLUME]) + 0
		formatString: #,0
		displayFolder: Customer Summary Measures
		lineageTag: fab647f3-bcb4-4571-a022-930279244bf4

	measure MktOvrview_TotalMMPatients = SUM('3 : HCP Data - LOT & Regimen Group'[Total MM Patients]) + 0
		formatString: #,0
		lineageTag: 0fc21c09-3ab2-4960-8c9e-9fd16fd4a916

	measure MktOvrview_TotalMMPatientsperAccountType = ```
			
			        CALCULATE(
			            SUM('3 : HCP Data - LOT & Regimen Group'[Total MM Patients]),
			            ALLEXCEPT('3 : HCP Data - LOT & Regimen Group','3 : HCP Data - LOT & Regimen Group'[Child Flag])
			        )
			```
		formatString: 0
		lineageTag: d4e3ab8a-c540-431b-9fa0-b88d768b7c4a

	measure MktOvrview_%Value = ```
			DIVIDE([MktOvrview_TotalMMPatients],[MktOvrview_TotalMMPatientsperAccountType],0) + 0 
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 5940329d-7fa6-4d40-8675-3b3d2161aa9e

	column Column1
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0376dcf5-d787-43b5-936e-9bbc27c8c59b
		summarizeBy: sum
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Calculation Group' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

